export enum QueryType {
  CHANGE = 'change',
  INREVIEW = 'inreview',
  PENDINGREVIEW = 'pendingreview',
  PENDINGREVIEWBYEDITOR = 'pendingreviewbyeditor',
  PENDINGREVIEWBYADMIN = 'pendingreviewbyadmin',
  INCOMPLETE = 'incomplete',
  ID = 'id',
  APPROVE = 'approve',
  APPROVED = 'approved',
  APPROVEBYEDITOR = 'statusupdate',
  STATUSCHANGE = 'semiapprove',
  APPROVEBYADMIN = 'approve',
  LATEST = 'latest',
  SEARCH = 'search',
  AUTHOR = 'author',
}
